Add EIP-6366: Permission Token (#6366)
* add permission token standard

* update the EIP follow the guideline

* update author name

* remove eip field

* eip field

* remove unnecessary sentence

* Update EIPS/eip-draft_permission_token.md

Co-authored-by: Pandapip1 <45835846+Pandapip1@users.noreply.github.com>

* Update EIPS/eip-draft_permission_token.md

Co-authored-by: Pandapip1 <45835846+Pandapip1@users.noreply.github.com>

* Update EIPS/eip-draft_permission_token.md

Co-authored-by: Pandapip1 <45835846+Pandapip1@users.noreply.github.com>

* Update EIPS/eip-draft_permission_token.md

Co-authored-by: Pandapip1 <45835846+Pandapip1@users.noreply.github.com>

* Update EIPS/eip-draft_permission_token.md

Co-authored-by: Pandapip1 <45835846+Pandapip1@users.noreply.github.com>

* Update EIPS/eip-draft_permission_token.md

Co-authored-by: Pandapip1 <45835846+Pandapip1@users.noreply.github.com>

* Update EIPS/eip-draft_permission_token.md

Co-authored-by: Pandapip1 <45835846+Pandapip1@users.noreply.github.com>

* Update EIPS/eip-draft_permission_token.md

Co-authored-by: Pandapip1 <45835846+Pandapip1@users.noreply.github.com>

* rename eip file

* Update EIP-6366 content and implement

* fix typo and add error interface

* Remove getAllDescription() method

* Add missing code highlight

* Update discussions-to link

* Update EIPS/eip-6366.md

Co-authored-by: Victor Dusart <43795504+vdusart@users.noreply.github.com>

* Update EIPS/eip-6366.md

Co-authored-by: Victor Dusart <43795504+vdusart@users.noreply.github.com>

* add function definition

* add missing s

* change argument name to match custom error argument

* This function is not pure

* change function name

* change return name

* Fix CI/CD check from EIP bot

* Fix implementation link

* regex match

* import implementations and exemples files

* remove external links

* Fix license and code format

* Fix include path

* Fix missing file due to different in path

* Fix CI/CD with ref ERC

Error: references to proposals with a `category` of `ERC` must use a prefix of `ERC`

* Fix file not

---------

Co-authored-by: Pandapip1 <45835846+Pandapip1@users.noreply.github.com>
Co-authored-by: Victor Dusart <43795504+vdusart@users.noreply.github.com>
Co-authored-by: Victor DUSART <dusartvictor@gmail.com>